apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflared
    namespace: notifications
spec:
    secretTemplates:
        - name: cloudflared-tunnel
          labels:
            app: n8n
          stringData:
            token: ENC[AES256_GCM,data:uT3BCDkAkiguQPwSMWXJZIMlgI1OrzOJSO2ULyVSpgPm6kEUZc+BTR0GaI0ak/ZVjAvzfSsJ7crpCMSFtaHf3qtFhKwHZOLblEpRajwQfDXdXcWGJcVSaadgbQSbHi+0aPGDlcPYj3HU2SpwHdqA2BWCYmxaadyPnlrLExfmQpA70tC+uMmY8kKY47v7h7UtsxR0yENnmJtGBrQ+drhcIAQx4BDtokR4ayCEGKlyRnecn421dxr7mjC1Mhn0Hbhx5pMefwMwXg7bbBwMZjeuq33U/R6uvBmAXGQqLHDNdq346nxPmBCFnyuRmJHNhkMVikv8bZIU3z0=,iv:WyfRhX4Wleo3Ror+Fp11XWn0dF5KJGoMH8zvhp5TEGs=,tag:4A2ytiowj9YCzrle95RGFA==,type:str]
sops:
    age:
        - recipient: age13486e9ss59pff6l0y6ktzxmp3sgwypxeyfpku2jl3jcxnd4lt35qgq8ktl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQXpRRFJrbUNEdXJPeFFy
            NEVFcmx5dElMMW1iS3Q5ZW9FVDR1bWFEcEVrCk5JRlBTZ25QbnlXNDEzVmhVYXNN
            NFJnTWQ2RnQvR2VIdm5vNkRzSkRINTQKLS0tIFJjSlh0YjNUR2t3Sk5wQkM5VzUx
            QUVHNU1tSTJuZXZHZ1NnMmw2eXg1NlEKjewQOubcUcOA91s2WJrDG6DUQb+eviRl
            6gPV/mLxxQLvvCIvD1N4dXwn6sOYT6LlMxF3VoqhC1UCaBbU07NAVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T09:16:26Z"
    mac: ENC[AES256_GCM,data:B8MUl5+JrXg04xVjb3uJ/lV9nY3+r89qtY1xZpPIir9JeoVIWzbp3OaAU6W0G30+aVmt41Nznl3l3RrqQcT5YaVBf4kQF0Bljp0jrsL6SMcRB93f5VRth12bql6Ma2q+53T9ZmH6R2nGz5vnKTQiXQ1EYFM3Q0dimtMOZapcbmg=,iv:AZ4gL2NKSmXLtDkG/RERffp0rka+4nAsyQuWZfjbZTk=,tag:hcm/xtcgF+oZBswYN9PWAA==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
