apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sonarqube-secrets
    namespace: sonarqube
spec:
    secretTemplates:
        - name: sonarqube-secrets
          labels:
            app.kubernetes.io/part-of: sonarqube
          stringData:
            jdbcPassword: ENC[AES256_GCM,data:2Z9RhWyv4LmLF6iZ/NiY69/pkbOlCBcGkTV5x4Y53w==,iv:wZ/EZV/I8Bc2GqukcjfbStq1MOsPxTPPrV8oTYFNzug=,tag:EXWLLN7RZayT/2G4BtJI4Q==,type:str]
            monitoringPasscode: ENC[AES256_GCM,data:w3yJL2E=,iv:zcTPrtW2mR8yq534PR2copt3TPMZ3jtG3sBKDtOFRys=,tag:p2SsKe2WXR+gik3rmviwVA==,type:str]
sops:
    age:
        - recipient: age13486e9ss59pff6l0y6ktzxmp3sgwypxeyfpku2jl3jcxnd4lt35qgq8ktl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZnh6QUtvUUVmRnNONEFp
            eUgwM3NPUGFYYWhvdFJVbTQ2QXZicUtZVzB3CkxZY0YzSXhJRzduMFB6ZVppM04r
            NnQ2ZnpCZUtXRUJrQmJCVHN2cnYvMVUKLS0tIFlQalpWM0VxNnJPNFY3dFdoZjVz
            cFRxSHRqSkt2TG5ib0YwMkFqMUVCc2MK/NMJCPVySLBdv96BZLh2rJ8gphgeuYCZ
            Z5fTnHCiaNplbGGExpOPHjv2MLFBD3VuopoGho0xbeAMsh5xX7/bfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T11:14:33Z"
    mac: ENC[AES256_GCM,data:vPcJAd2aRlpa0IC0b1lqRwi3FwV2g3z/uHIDlE45IrjbocyvnbkvWWTXinEO+5jA+pLNKG1sFTD/8tDeMm9ZgpZP3Pa1decAItXghAzeZqDcByH0yL8PqaxvjT30mkaE7Dm8fZZO+gZho+SUqkz2VQh6RII16uVaidtydRR1CK4=,iv:KcvhR2oa5vYfZckJi9GE8ghA+1qSJu3F2v8H3IUr4hM=,tag:mAEzIKxThHLZguPzcc9taA==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
