apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ramesh-portfolio
  name: ramesh-portfolio
  namespace: ramesh-portfolio
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ramesh-portfolio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ramesh-portfolio
    spec:
      containers:
      - name: nginx
        image: registry.markklass.dev/misc/ramesh_portfolio:main-1782543999-0005832 # {"$imagepolicy": "flux-system:ramesh-portfolio"}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 20
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 64Mi
      imagePullSecrets:
      - name: gitlab-registry
