apiVersion: v1
data:
  datasources.yaml: "apiVersion: 1\ndatasources:\n  - name: Prometheus\n    type:\
    \ prometheus\n    uid: prometheus\n    access: proxy\n    url: http://prometheus:9090\n\
    \    isDefault: true\n    editable: false\n    jsonData:\n      timeInterval:\
    \ \"30s\"\n      httpMethod: POST\n  - name: Alertmanager\n    type: alertmanager\n\
    \    uid: alertmanager\n    access: proxy\n    url: http://alertmanager:9093\n\
    \    editable: false\n    jsonData:\n      implementation: prometheus\n  - name:\
    \ Loki\n    type: loki\n    uid: loki\n    access: proxy\n    url: http://loki:3100\n\
    \    editable: false\n    jsonData:\n      derivedFields:\n        - datasourceUid:\
    \ prometheus\n          matcherRegex: \"namespace=\\\"(.*?)\\\"\"\n          name:\
    \ namespace\n          url: \"\"\n"
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
