apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/ip-allocated-from-pool: first-pool
    metallb.universe.tf/allow-shared-ip: monitoring-stack
  labels:
    app: loki
  name: loki
  namespace: monitoring
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 10.0.0.121
  ports:
  - name: http
    nodePort: 31758
    port: 3100
    protocol: TCP
    targetPort: http
  selector:
    app: loki
  sessionAffinity: None
  type: LoadBalancer
