apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bentopdf
  name: bentopdf
  namespace: bentopdf
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bentopdf
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bentopdf
    spec:
      containers:
      - name: bentopdf
        image: ghcr.io/alam00000/bentopdf-simple:2.8.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 20
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi
