apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.104
  labels:
    app: bentopdf
  name: bentopdf
  namespace: bentopdf
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: bentopdf
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
