apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-timezone
spec:
  rules:
    - name: inject-tz-env
      match:
        any:
          - resources:
              kinds:
                - Pod
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    env:
                      - name: TZ
                        value: Asia/Singapore
