apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hadash
    namespace: hadash
spec:
    secretTemplates:
        - name: hadash-config
          labels:
            app: hadash
          stringData:
            HA_URL: ENC[AES256_GCM,data:LxN6e4D6baVdt9f0aLOpdATv41WpoEIy,iv:PS6DFpIUdY7AWlLyFTYghfEVwnVd4/dQOX84360cAss=,tag:trJUgENKlcJMpDDanxfrgg==,type:str]
            HA_TOKEN: ENC[AES256_GCM,data:dmLHsvvbmUTDe/rRSZy2hHUlQujWY4v+c4fhbfDp9elvOl5jjiWxYiVTdtOnqxWEgDTaBiNc7aFIdl4lpPt7Hp76zh1hrzyAgwF/AAEUYQ/BzOL40oWaOxGwLjAkYQB+OlBkWO9R/LhzF1mILLtLGFTQMcp9PgExwAFPuMTddD3Gxlujw5vPiXqAekujRv2BM+40BnQtFljvtzuJCeTjLGnaLEwKbSZmBeOf20gSWLifO2yhdcSP,iv:fj0Nhgnh6T0YCDbTgHS6mkakokvk1AeshqepUy5Qxfg=,tag:NBr6oQsBcUulP/9GoOQU2Q==,type:str]
sops:
    age:
        - recipient: age13486e9ss59pff6l0y6ktzxmp3sgwypxeyfpku2jl3jcxnd4lt35qgq8ktl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyc0NJRFJYbElOUFBwMVN6
            UHZTQVBkeVl0aXIyYjZ1NDY0SmhIMi9tMGlzClYyUjBWdGd4aTdnNHZYWUpqbHM2
            QjVDdlpuVHVDZWtaSEorQmpDYTQ5NXMKLS0tIHVleFN1Q2dnWGczNVZaUmdKNFZw
            R21UVHlKaVFjOE9uZWZjSExibTVqMDQKw1SasMIzU4AA9KSxlASMGONCKtQd0Hg7
            JluQWDtxIBZl4FH+K429PDlm8hUYrskOWcV1Min1xal+TfQ/+oOOfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T12:43:22Z"
    mac: ENC[AES256_GCM,data:MaRJf8eYOAQWDh5XQpQxaffPVUai7IryBwjkkYhN2bGkEJkBoIGggCMiL9GHPyV62IiCAK1BLW7aj++Q0JWYXtIuq7Dd6dSEohtFr3lhV0G3wiNvTtnORvR8zrXDHvgdOwGwZI2lMv6/L3wgMhUUy4TulMJkqNaC2/kwlElxlg0=,iv:/JJRd7PI7Hb6vsSJgH0BDwGq39ro3wrlwtOGD5RP/QM=,tag:AmJ6vcD67vkqfvaYrWsB1Q==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
