apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - image-automation.yaml
  - images-hadash.yaml
  - images-kopilog.yaml
  - images-ramesh-portfolio.yaml
  - images-resume.yaml
