apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmaps.yaml
  - cronjob.yaml
  - deployment.yaml
  - freshness-probe.yaml
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - sopssecret-kopilog.sops.yaml
