apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.122
  labels:
    app: kopilog
  name: kopilog-web
  namespace: kopilog
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30810
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kopilog
    component: web
  sessionAffinity: None
  type: LoadBalancer
