apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: kopilog
    namespace: kopilog
spec:
    secretTemplates:
        - name: kopilog-git
          labels:
            app: kopilog
          stringData:
            token: ENC[AES256_GCM,data:4vTUMpksZ7utHnkcfBcetOs2lm6R8Z7JNGdnPilwwNeD9bEMdP+VB0jckyCwzyG8KI5k,iv:XTbZQy6hYDhGdDfENxYPTYA+T0gMWYk8i5ofkWjJWYA=,tag:KxhZe/ah1ixsx1zSiNtEJQ==,type:str]
        - name: kopilog-secrets
          labels:
            app: kopilog
          stringData:
            PEXELS_API_KEY: ENC[AES256_GCM,data:+gUmBDND1o/vS80bzmOyGGplycBIE+t+fJyWMjjsoCAQRz9GU4Pj0dKeYvNSrp0wSklJB1EUmXg=,iv:OSqJT2PKTzg6hIMHQURKyk3Cbf2GJtsPLEVC+VQ7mtQ=,tag:4OOSTVVIn8dvINtsnvAHQg==,type:str]
sops:
    age:
        - recipient: age13486e9ss59pff6l0y6ktzxmp3sgwypxeyfpku2jl3jcxnd4lt35qgq8ktl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y3BHNVdwa3N0VklESTl6
            RXFBQzhOWXRWZktmdTYwY0p0SjNaTFVPendRCmk1L1NTYXF0MlJiZHo4ZHpzdkpW
            TDVPODJYTExLVDBHdFcrS2J6N3pmUjQKLS0tIEJxbmtqaFFuQ0VjNU9EUWNsZHN5
            Q0ZydjRWMlF3T0xsZk5TTGVHeHVoWVkKbTZCwxgJuiXpR2IVNA7IFI3ewZhvvfJu
            ySFip9Ch/KGV3qTYFVEkMlxZ6L0kLVj0W84RsZ1igUcKu513aln6pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T05:19:57Z"
    mac: ENC[AES256_GCM,data:y5CzIdDYV0rrt+WtQKLW24N9ijho9YWGpeFy92LOCXDhTbfSbqVEsndRT+lHLh+sY0JfTS7IJTJNHtlmadO27C0GlsVNlC5tB4S+GVA9khGuge+ZsDpRLYjYC7KE2aARdPPDGIZp6uOuFDknrck5ZPHhtAwDDFjzkehFiuXWvTA=,iv:UamkaLZsac9h/3iyq1adUuqJq+KfLn45ERs+50N5Fp0=,tag:jSuSqhGQ5+/+NkMXAB6KaQ==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
